apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: {{ .Release.Name }}-metrics
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
  {{- range $key, $value := .Values.serviceAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
   app.kubernetes.io/part-of: {{ .Release.Name }}
    {{- if .Values.controller.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.controller.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
  {{- if .Values.controller.metrics.serviceMonitor.additionalAnnotations }}
  annotations:
{{ toYaml .Values.controller.metrics.serviceMonitor.additionalAnnotations | indent 4 }}
  {{- end }}
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8090
    targetPort: 8090
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
